### ISSUE TITLE
Scientific notation for max and min values in analog channels does not work

### ISSUE THREAD

**Issue by nilsakesson** [gemstone/comtrade#6]
--- file type: CFG ---
My Unit,My Product,2013
3,3A,0D
1,Ia,L1,,A,1.000000,0.000000,0,–3.4028235E38,3.4028235E38,300,1,P
2,Ib,L2,,A,1.000000,0.000000,0,–3.4028235E38,3.4028235E38,300,1,P
3,Ic,L3,,A,1.000000,0.000000,0,–3.4028235E38,3.4028235E38,300,1,P
.
.
.

Parser fails from max and min values in scientific notation with an E like in the example above.

According to standard it should work:

max is the range maximum data value (upper limit of possible data value range) for
data values of this channel. Critical, numeric (integer or real), minimum length
= 1 character, maximum length = 13 characters, minimum value =
–3.4028235E38, maximum value = 3.4028235E38. Note: max > min always.

**Comment by StephenCWills** [comment]
I tried parsing the examples you listed. Scientific notation works fine, but for negative numbers you need to use Hyphen-Minus `-` (U+002D) rather than En Dash `–` (U+2013).

**Comment by nilsakesson** [comment]
Ahh, copied it straight out of the standard document, thanks!
