### ISSUE TITLE
Timestamps are still failing to parse due to not being parsed with CultureInfo.InvariantCulture flag

### ISSUE THREAD

**Issue by nilsakesson** [gemstone/comtrade#7]
Timestamps are still not being parsed correctly in timestamp.cs as in #2 
If formatted as standard 
dd/mm/yyyy,hh:mm:ss.ssssss
the fraction parts of a second are failing due to the dot not being accepted
Example timestamp is:

01/11/2024,13:22:18.000156

the snippet 

```
            TryParse(parts[^1], out double seconds);

            seconds += milliseconds;

            parts[^1] = seconds.ToString("00.000000");
```

should be changed to 

```
           double.TryParse(parts[^1], NumberStyles.Float, CultureInfo.InvariantCulture, out double seconds);

            seconds += milliseconds;

            parts[^1] = seconds.ToString("00.000000", CultureInfo.InvariantCulture);
```

on row 66-70

**Comment by StephenCWills** [comment]
The `TryParse()` method in `Timestamp.cs` looks like this.

https://github.com/gemstone/comtrade/blob/a925b19953b8cd89cd62b1ad3d4c5ad43f857523/src/Gemstone.COMTRADE/Timestamp.cs#L103-L108

It's already using `NumberStyles.Float` and `CultureInfo.InvariantCulture`. The only difference is that it also includes `NumberStyles.AllowThousands`. Therefore, I believe the only fix we should need is to add `CultureInfo.InvariantCulture` to the call to `seconds.ToString()`.
